services:
  backend:
    # переопределяем только backend для dev
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg2://app:app_password_change_me@postgres:5432/appdb
      JWT_SECRET: CHANGE_ME_SECRET
      JWT_EXPIRES_MIN: "4320"
    volumes:
      - ./backend/app:/app/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
